### ISSUE TITLE
Trouble with train quick 96, SAEHD in DeepFaceLab

### ISSUE THREAD

**Issue by DynaRIT** [RedHatInsights/insights-results-aggregator-mock#312]
I tryd to train quick 96, an error appeared Error: No training data provided.
Traceback (most recent call last):
  File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug)
  File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12\_internal\DeepFaceLab\models\ModelBase.py", line 193, in __init__
    self.on_initialize()
  File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 240, in on_initialize
    generators_count=src_generators_count ),
  File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 48, in __init__
    raise ValueError('No training data provided.')
ValueError: No training data provided.

**Comment by tisnik** [comment]
Hi @DynaRIT . Is it really an issue connected with this repository? Seems like you use wrong repo perhaps...

**Comment by DynaRIT** [comment]
> Hi @DynaRIT . Is it really an issue connected with this repository? Seems like you use wrong repo perhaps...

What do you mean by repository and repo?

**Comment by tisnik** [comment]
@DynaRIT you filled an issue against github.com/RedHatInsights/insights-results-aggregator-mock repository (or project if you wish). But your problem seems to be unrelated to this repo/project.

**Comment by DynaRIT** [comment]
> @DynaRIT you filled an issue against github.com/RedHatInsights/insights-results-aggregator-mock repository (or project if you wish). But your problem seems to be unrelated to this repo/project.

Yes, unrelated

**Comment by tisnik** [comment]
@DynaRIT probably this is the right repository? https://github.com/iperov/DeepFaceLab

**Comment by DynaRIT** [comment]
> @DynaRIT you filled an issue against github.com/RedHatInsights/insights-results-aggregator-mock repository (or project if you wish). But your problem seems to be unrelated to this repo/project.

It is worth noting that this problem appeared after I started the game during DeepFake processing, and DeepFake processing stopped.

**Comment by tisnik** [comment]
@DynaRIT the thing is, that we as authors of RedHatInsights/insights-results-aggregator-mock project are unable to help you with DeepFace SW (or what you actually use). You need to fill in an issue against the right repository/project to get proper help.
